import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SupabaseProvider } from "@/Context/supabaseContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lavin Elektriska",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabaseHostname = (() => {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
    try {
      return url ? new URL(url).hostname : null;
    } catch {
      return null;
    }
  })();
  return (
    <html lang="en">
      <head>
        {supabaseHostname && (
          <>
            <link rel="preconnect" href={`https://${supabaseHostname}`} crossOrigin="anonymous" />
            <link rel="dns-prefetch" href={`//${supabaseHostname}`} />
          </>
        )}
      </head>
      <SupabaseProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
      </SupabaseProvider>
    </html>
  );
}
